version: '3.1'
services:
  postgresqldb:
    image: postgres
    container_name: graphql-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: testdb
      DB_ADDRESS: postgresqldb # OR URL
      DB_PORT: 5432