apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-depl
spec:
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: mohamed/graphql-app


---
apiVersion: v1
kind: Service
metadata:
  name: graphql-srv
spec:
  selector:
    app: graphql
  ports:
    - name: graphql
      port: 8080
      protocol: TCP
      targetPort: 8080
