name: graphql
on :
  push :
    branches:
      - master
jobs:
  build-deploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name : build
        run : |
          mvn clean 
          mvn -B package --file pom.xml
          mvn compile jib:build -Djib.to.auth.username=${{secrets.DOCKER_HUB_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_HUB_PASSWORD}}
